<?php

/**
 * Implements hook_rest_resource_alter().
 */
function custom_api_rest_resource_alter(&$definitions) {
    // Check if the resource is the node entity.
    echo "<pre>";
    print_r($definitions[0]);
    die('----hi----');
    if ($definitions[0] == 'entity:node') {
        // Alter the GET method callback.
        if (isset($resource_routes['get'])) {
            $resource_routes['get']['callbacks'][] = '_custom_node_get';
        }
    }
}

/**
 * Custom callback for GET method of the node entity.
 */
function _custom_node_get() {
    // Custom logic here.
}
